project:
  type: website
  output-dir: docs
  render:
    - "**/*.qmd"
    - "!academic-cv/"

# Meta
description-meta: "Academic Website for Basant saud"
author-meta: "Basant saud"

website:
  page-navigation: true
  title: "Basant saud"
  image: "files/profiles/basant.png"
  favicon: "/files/profiles/icon.png"
  description: "Academic Website for Basant saud"

  page-footer:
    center: "&copy; Copyright 2026, Basant saud"
    
  navbar:
    pinned: true
    left:
      - href: index.qmd
        text: Home
      - href: about/index.qmd
        text: About
      - text: Research
        menu:
          - href: research/index.qmd
            text: Overview
          - href: projects/index.qmd
            text: Projects
      - href: tutorials/index.qmd
        text: Tutorials
      - href: blog/index.qmd
        text: Blog
      - href: publications/index.qmd
        text: Publications
      - text: CV
        href: cv/


# some important configs 
site-url: "https://saudbasant.github.io/"
search: false
reader-mode: true
draft-mode: unlinked
  
# google analytics 
google-analytics:
    tracking-id: ""
    anonymize-ip: true
    
    
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-expand: 1
    mermaid:
      theme: neutral



