project:
  type: website
  output-dir: docs
  render:
    - "**/*.qmd"
    - "!academic-cv/"

# Meta
description-meta: "Academic Website for Basant saud"
author-meta: "Basant saud"

website:
  page-navigation: true
  title: "Basant saud"
  image: "files/profiles/basant1.webp"
  favicon: "/files/profiles/icon.png"
  description: "Academic Website for Basant saud"

  page-footer:
    center: "&copy; 2026 Basant saud. Last updated: September 17, 2026"
    
  navbar:
    pinned: true
    left:
      - href: index.qmd
        text: Home
        
      - href: about/index.qmd
        text: About
        
      - text: Research
        menu:
          - href: research/index.qmd
            text: Overview
          - href: projects/index.qmd
            text: Projects
            
      - href: portfolio/index.qmd
        text: Portfolio
        
      - href: tutorials/index.qmd
        text: Tutorials
        
      - href: blog/index.qmd
        text: Blog
        
      - text: Notes
        menu: 
          - href: notes/linux/
            text: Linux
          - href: notes/R/
            text: R
            
      - href: publications/index.qmd
        text: Publications
        
      - href: cv/
        text: CV
        


# some important configs 
site-url: "https://saudbasant.github.io/"
search: false
reader-mode: true
  
# google analytics 
google-analytics:
    tracking-id: ""
    anonymize-ip: true
    
    
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-expand: 1
    mermaid:
      theme: neutral



